# workflow -> Pipeline
# workflow name
name: CD Pipeline

# event on which you want this pipeline to be triggered
on:
  push:
    branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs
jobs:
    # job name
  deploy:

    # server
    runs-on: ubuntu-latest
    # versions you want to test your app on
    # strategy:
    #   matrix:
    #     node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
        # switch branch - (main)
    - uses: actions/checkout@v4
    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: ${{ matrix.node-version }}
    #     cache: 'npm'
    #     # actual command
    - name : Build Docker Image
      run: docker build -t nehal524/youtube-backend:latest .

    - name: "Build Successful"
      run: echo "Docker Image built successfully"
# docker hub - 2367te346tr3t2ewyquert7yer
    - name: Docker Login
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Login Successful'
      run: echo "Logged in to Docker Hub successfully"

    - name: Push Docker Image
      run: docker push nehal524/youtube-backend:latest

  aws-deploy:

    # aws server - ec2 instance
    needs: deploy
    runs-on: self-hosted

    steps:
        # switch branch - (main)
    - uses: actions/checkout@v4

    # step 1
    - name : pull latest docker image
      run: docker pull nehal524/youtube-backend:latest
    #  step 2
    - name: Remove exsisting container
      run: docker rm -f yt-backend || true
      
    - name: Remove exsisting container
      run: docker rm -f redis || true
# docker hub - 2367te346tr3t2ewyquert7yer

    - name: Run Redis inside container
      run: docker run -d --name redis redis:latest

    - name: Run Docker Cointainer for YT-Backend App
      run: docker run -d --name yt-backend --link redis:redis -p 4000:4000 -e MONGO_URI="${{secrets.MONGO_DB_URI}}"  nehal524/youtube-backend:latest













  
